workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: '$CI_PIPELINE_SOURCE == "push"'

image: node:current-alpine3.12

stages:
  - build
  - test

cache:
  key: ${CI_JOB_NAME}-cache-1611917650
  paths:
    - node_modules

test:
  stage: build
  variables:
    CHROME_BIN: "/usr/bin/chromium-browser"
    CHROME_PATH: "/usr/lib/chromium/"
    FIREFOX_BIN: "/usr/bin/firefox"
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
    PUPPETEER_SKIP_FIREFOX_DOWNLOAD: "true"
  script:
    - apk add chromium chromium-chromedriver firefox
    - npm install
    - npm run build
    - npm run lint
    - npm test
    - PUPPETEER_PRODUCT=firefox npm test
