workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: $CI_MERGE_REQUEST_IID
    - if: '$CI_PIPELINE_SOURCE == "push"'

image: node:current-alpine3.13

stages:
  - test
  - release

cache:
  key: ${CI_JOB_NAME}-cache-1611917650
  paths:
    - node_modules

lint:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: '$CI_PIPELINE_SOURCE == "push"'
  stage: test
  before_script:
    - npm install
  script:
    - npm run lint

test:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: '$CI_PIPELINE_SOURCE == "push"'
  stage: test
  variables:
    CHROME_BIN: "/usr/bin/chromium-browser"
    CHROME_PATH: "/usr/lib/chromium/"
    FIREFOX_BIN: "/usr/bin/firefox"
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
    PUPPETEER_SKIP_FIREFOX_DOWNLOAD: "true"
  before_script:
    - apk add chromium chromium-chromedriver firefox
  script:
    - npm install
    - npm run build
    - npm test
    - PUPPETEER_PRODUCT=firefox npm test

security:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: $CI_MERGE_REQUEST_IID
    - if: '$CI_PIPELINE_SOURCE == "push"'
  stage: test
  script:
    - npm audit --audit-level=low

release:
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v/'
  before_script:
    - echo '@drupal:registry=https://registry.npmjs.org/' > ~/.npmrc
    - echo '//registry.npmjs.org/:_authToken=${NPM_ACCESS_TOKEN}' >> ~/.npmrc
  script:
    - npm install
    - npm version $(echo ${CI_COMMIT_TAG} | cut -c2-) --no-git-tag-version
    - npm run build
    - npm publish --access public
