changesetBaseRefs:
  - main
  - origin/main

packageExtensions:
  "@open-wc/testing@*":
    dependencies:
      sinon: "*"
  "@web/dev-server@*":
    dependencies:
      rollup: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
