plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  '@open-wc/testing@*':
    dependencies:
      'sinon': '*'
  '@web/dev-server@*':
    dependencies:
      'rollup': '*'
